# A Multivariable Regressor

重回帰分析……多次元のデータを扱う。

In [1]:
import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm

input_file = 'const/data_multivar_regr.txt'
data = np.loadtxt(input_file, delimiter=',')
X, y = data[:, :-1], data[:, -1]

regressor = linear_model.LinearRegression()
regressor.fit(X, y)
y_pred = regressor.predict(X)

In [2]:
print('** Liner regressor performance **')
print('Mean absolute error = ', round(sm.mean_absolute_error(y, y_pred), 2))
print('Mean squared error = ', round(sm.mean_squared_error(y, y_pred), 2))
print('Median absolute error = ', round(sm.median_absolute_error(y, y_pred), 2))
print('Explain variance score = ', round(sm.explained_variance_score(y, y_pred), 2))
print('R2 score = ', round(sm.r2_score(y, y_pred), 2))

** Liner regressor performance **
Mean absolute error =  3.64
Mean squared error =  20.9
Median absolute error =  3.1
Explain variance score =  0.86
R2 score =  0.86


In [3]:
print('Liner regression:')
print(regressor.predict(X[0: 5]))
print('True output values:')
print(y[0: 5])

Liner regression:
[10.82449559 17.3818526   3.29725309 38.64955824 10.41302956]
True output values:
[15.69 15.34  0.66 38.37  9.96]


訓練用データとテストデータを分けて学習してみる。

In [4]:
from sklearn import model_selection

X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.01)

new_regressor = linear_model.LinearRegression()
new_regressor.fit(X_train, y_train)

new_y_pred = new_regressor.predict(X_train)

In [5]:
print('** Liner regressor performance **')
print('Mean absolute error = ', round(sm.mean_absolute_error(y_train, new_y_pred), 2))
print('Mean squared error = ', round(sm.mean_squared_error(y_train, new_y_pred), 2))
print('Median absolute error = ', round(sm.median_absolute_error(y_train, new_y_pred), 2))
print('Explain variance score = ', round(sm.explained_variance_score(y_train, new_y_pred), 2))
print('R2 score = ', round(sm.r2_score(y_train, new_y_pred), 2))

** Liner regressor performance **
Mean absolute error =  3.64
Mean squared error =  20.8
Median absolute error =  3.14
Explain variance score =  0.86
R2 score =  0.86


In [6]:
print('Liner regression:')
print(regressor.predict(X_test))
print('True output values:')
print(y_test)

Liner regression:
[23.41113716 22.68919595 33.73855764 30.66836272 20.704205   -1.33607187
 27.30633772]
True output values:
[25.95 17.21 45.58 31.71 20.97 -6.79 28.31]
